### ISSUE TITLE
Configuring startup settings on a device in the server

### ISSUE THREAD

**Issue by juliomateoslangerak** [python-microscope/microscope#266]
I need to be able to configure the initial settings of a device. Users do not want to go through a list of settings to chose the different options that are always the same at startup. In my case this involves 5 settings per camera, including a 2-3 applies. 

According to the documentation this is achieved through adding a function to the DEVICES list in the config file. However this is not working under Windows (at least for the moment). #179 

Independently of the need of sending a function to the device server, I was wondering if it would be possible to add another dict argument to the device to configure the settings after initialization. For example ```initial_settings = {"read_speed": "100MHz", "sensor_temperature": "-10",...}```.
At the moment, the ```conf``` argument is easily confused with this purpose.

**Comment by carandraug** [comment]
I guess something like that could be added, but since you are using cockpit, why not specifying it on the depot file? Something like this should work (the settings named need to be indented):

```
[south camera]
type: cockpit.devices.microscopeCamera.MicroscopeCamera
uri: whatever url
settings:
    some-option-name = some value
    some-other-option = some other value 
```

**Comment by juliomateoslangerak** [comment]
That's great, I was not aware of this feature. I looked for it and I cannot find it documented. Is it?
Just note that the ```=``` is not working. You have to use the colon ```:``` notation to separate key and value. This is my example depot for a camera:
```
[Green-Cam]
type: cockpit.devices.microscopeCamera.MicroscopeCamera
uri: PYRO:AndorSDK3@10.6.19.31:8001
transform: (1, 1, 1)
triggerSource: cRIO
triggerLine: 4
settings:
    aoi_height: 1024
    aoi_width: 1024
    aoi_left: 513
    aoi_top: 513
    pixel_readout_rate: 100 MHz
    simple_pre_amp_gain_control: 16bit (low noise & high well capacity)
    trigger_mode: External Exposure
```
I guess the question of weather we need this kind of functionality on microscope too remains
